name: CI

on:
  push: # Trigger on any branch commit
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  test:
    name: Test Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          ./gradlew test